source "https://rubygems.org"

# Specify your gem's dependencies in tabler_view_components.gemspec.
gemspec path: "../"

gem "puma"
gem "rails", ">= 7.2"

gem "sqlite3"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"


# preview
gem "lookbook", ">= 2.3.13"
gem "listen"
gem "actioncable"

gem "reactionview"
